### ISSUE TITLE
Raw property names with camelCase rename result in misgenerated typescript property names

### ISSUE THREAD

**Issue by partiallyordered** [Aleph-Alpha/ts-rs#27]
Thanks for this package, I'm finding it very useful for sharing a protocol between Rust and ts. I hate to create an issue instead of a PR, but I can't spare the time to make a PR right now. So here goes:

Cargo.toml:
```toml
[package]
name = "blah"
version = "0.1.0"
edition = "2018" 

[dependencies]
ts-rs = "3.0.0"
```

src/main.rs:
```rust
use ts_rs::{TS, export};

#[derive(TS)]
#[ts(rename_all = "camelCase")]
struct User {
    r#type: i32,
}

export! {
    User => "bindings.ts"
}
```

Result bindings.ts:
```
export interface User {
  rType: number;
}
```

Specifically, `rType` in the output. I note that the bindings aren't generated at all without `rename_all = "camelCase"`. The workaround I'm currently using is to use `#[ts(rename = "type")]` on the relevant field.
