### ISSUE TITLE
Type definitions on enums

### ISSUE THREAD

**Issue by JonasFocke01** [Aleph-Alpha/ts-rs#352]
I have a enum, where some of its variants contain nested data. Some of that data are foreign structs that do not impl the TS trait.

Inside structs we have the possibility to use attributes like `#[ts(type = "Vec<usize>)]` for this case, but this attribute fails on enums telling me `type` is unknown and only these are allowed: `"rename", "rename_all", "inline", "skip", "untagged"`.

I could implement TS on these structs, but that would require me to write some boilerplate.

Here is a minimal setup of my usecase:
```rust
use serde::{Deserialize, Serialize};
use time::{Duration, Weekday};
use ts_rs::TS;

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[ts(export)]
pub enum MyEnum {
    // #[ts(type = "Vec<isize>")]
    Variant1(Duration), // time::Duration does not impl TS
    Variant2(usize),
    // #[ts(as = "[usize, String]")]
    Variant3((usize, Weekday)), // time::Weekday does not impl TS
}

fn main() {
    println!("Hello, world!");
}
```

```toml
[package]
name = "rust-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
ts-rs = "9.0.1"
serde = { version = "1.0.182", features = ["derive"] }
time = { version = "0.3.31", features = ["serde", "local-offset", "parsing", "formatting"] }
```
